<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-5G9L95S0" ignored="2" name="Test" tests="3" failures="1" timestamp="05 Mar 2020 11:42:51 GMT" time="38.323" errors="0">
  <testcase name="verifyLoginPage" time="0.064" classname="Pages.LoginTest"/>
  <testcase name="checkErrorMessage1" time="0.549" classname="Pages.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Please enter email as kiran123@gmail.com] but found [Please enter email as kiran@gmail.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Please enter email as kiran123@gmail.com] but found [Please enter email as kiran@gmail.com]
	at Pages.LoginTest.checkErrorMessage1(LoginTest.java:65)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- checkErrorMessage1 -->
  <testcase name="SigUpTest" time="0.407" classname="Pages.SignUp"/>
  <testcase name="@BeforeSuite getInstance" time="0.0" classname="baseController.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite getInstance -->
  <testcase name="@AfterSuite tearDownMethod" time="0.0" classname="baseController.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownMethod -->
</testsuite> <!-- Test -->
